name: Firebase Continuous Deployment

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12
      - name: Install and Build 🔧
      - run: npm install @vue/cli
      - run: npm ci --prefix ./frontend
      - run: npm run build --prefix ./frontend
      - name: Deploy 🚀
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          # you can retrieve this token by running ```firebase login:ci```
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
